### ISSUE TITLE
Training procedure.

### ISSUE THREAD

**Issue by Akhilesh64** [feevos/resuneta#10]
How do I replicate the training procedure you followed. I have the postdam dataset available with me. How do I preprocess the dataset to feed into the model.

**Comment by feevos** [comment]
Hi @Akhilesh64 , thank you for your interest in our work. 

You have to: a) concatenate the optical with the DSM and create a 5 channel image R-G-B-NIR-DSM b) chop it up in training chips of size 5x256x256. In the file https://github.com/feevos/resuneta/blob/master/src/ISPRSNormal.py exist information on means/stds for normalization of the training chips. Chopping the full rasters into training chips can be achieved with code located in  https://github.com/feevos/resuneta/blob/master/src/chopchop_run.py 

I don't remember which DEM model we used. You may also find this tutorial a bit useful for understanding the data: https://www.linkedin.com/pulse/semantic-segmentation-tutorial-mxnetgluon-part-i-foivos-diakogiannis/   

Hope this helps.

**Comment by Akhilesh64** [comment]
Thanks this helps a lot.
