### ISSUE TITLE
distance

### ISSUE THREAD

**Issue by long123524** [feevos/resuneta#12]
Hello, I would like to ask how you obtained the distance map as training data? Does it need to go through special pre-procesing? Can you share your experience?

**Comment by feevos** [comment]
Hi @long123524 , [line 80](https://github.com/feevos/resuneta/blob/49d26563f84c737e07d34edfe30b56c59cbb4203/src/chopchop_run.py#L80) has what you are after. No special pre-processing other than translating the labels to 1hot encoding. 

Regards.
