### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by tingtingqu** [feevos/resuneta#14]
Hello, I've just come into contact with academics. What I want to ask is how to train and test data without train.py.

**Comment by feevos** [comment]
Hi @tingtingqu you need to understand how to use mxnet and see example training scripts from the mxnet source code base. If you are familiar with pytorch, it is quite similar. Some useful resources are: 

1. d2l.ai
2. https://mxnet.apache.org/versions/1.8.0/api/python/docs/tutorials/ 
3. https://mxnet.apache.org/versions/1.8.0/api/python/docs/tutorials/packages/gluon/index.html 
4. https://medium.com/apache-mxnet/mxnet-gluon-in-60-minutes-3d49eccaf266 
5. https://github.com/apache/incubator-mxnet/tree/master/example/gluon/mnist 

See also the forum for questions: 
1. https://discuss.mxnet.apache.org/
2. https://github.com/apache/incubator-mxnet/discussions 

Once you know the basics of mxnet, then you can write your own custom training routine, download the data that this repository refers to etc. That is you need to: 
1. Get the data
2. Chop it into training chips as described in our manuscript
3. Use the Dataset class provided as well as the data augmentation
4. Use the model developed here, in your own training script 
4. run your training script
5. Write your own inference script and test the performance on test data.  

The purpose of this repository is to have demo/example code so one can reproduce the steps we took into our research paper. It is not a software for usage as a black box. Therefore you'll need to spend time to learn mxnet. 

Regards,
Foivos

**Comment by tingtingqu** [comment]
Thank you very much. I already know the problem------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月2日(星期四) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [feevos/resuneta] train.py (#14)
