### ISSUE TITLE
Different dataset

### ISSUE THREAD

**Issue by henrique-vb** [feevos/resuneta#15]
Hi Feevos, 
I'm using your architecture, and I would like to change my image space. I'm making a test with Potsdam dataset normalized between [0-1] and I don't change masks.
So, I change ISPRSnormal.py to my own dataset, with values between 0-1, but I didn't perform well. Do I need to change something else?

I'm doing this in this dataset to learn how the insertion of this type of data in the architecture works.
Thanks!

**Comment by feevos** [comment]
Hi @henrique-vb  I think you may need to pay attention to the random transformations that take place, in file [semseg_aug_cv2.py](https://github.com/feevos/resuneta/blob/master/src/semseg_aug_cv2.py). I don't remember how I was saving the data, but looking at the Dataset definitions, they are not normalized, they are normalized within the dataset call, which suggests they may be in uint8 when I am reading them. So if your code is in 0,1 it maybe that after random augmentation the input signal is destroyed. Not sure though. 

You can try: 
1.  Load your dataset class WITH data augmentation included and visualize both the inputs and the masks, to see any differences. 
2. If this produces problems comment out in [line 32](https://github.com/feevos/resuneta/blob/master/src/semseg_aug_cv2.py) of the semantic segmentation (then the only transformations left will be random reflections 

I cannot think of anything else. The model is agnostic, so if there is an error it is in the combo of files under directory src, the Dataset definition, the normalization and the random augmentation with emphasis when going from uint8 to float32. 

Best of luck!

**Comment by henrique-vb** [comment]
Why can't I run the rotations? the center range is the same... Is it due to the input data type (uint8 and float32)?
I'm having the following traceback even on a dataset in the 0-255 range. Would I need to convert my images to uint8 before cutting them?

> Traceback (most recent call last):
>   File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
>     result = (True, func(*args, **kwds))
>   File "/usr/local/lib/python3.7/dist-packages/mxnet/gluon/data/dataloader.py", line 429, in _worker_fn
>     batch = batchify_fn([_worker_dataset[i] for i in samples])
>   File "/usr/local/lib/python3.7/dist-packages/mxnet/gluon/data/dataloader.py", line 429, in <listcomp>
>     batch = batchify_fn([_worker_dataset[i] for i in samples])
>   File "/content/gdrive/MyDrive/Colab Notebooks/resuneta/src/ISPRSDataset.py", line 86, in __getitem__
>     base, mask = self._transform(base, mask)
>   File "/content/gdrive/MyDrive/Colab Notebooks/resuneta/src/semseg_aug_cv2.py", line 113, in __call__
>     return next(self.iterator)(_img,_mask)
>   File "/content/gdrive/MyDrive/Colab Notebooks/resuneta/src/semseg_aug_cv2.py", line 105, in rand_shit_rot_zoom
>     return self._shift_rot_zoom(_img,_mask,tuple(center),angle,scale) #, tuple(center),angle,scale
>   File "/content/gdrive/MyDrive/Colab Notebooks/resuneta/src/semseg_aug_cv2.py", line 50, in _shift_rot_zoom
>     tRotMat = cv2.getRotationMatrix2D(_center, _angle, _scale)
> TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type


Oh, and thanks for the help!

**Comment by henrique-vb** [comment]
> Why can't I run the rotations? the center range is the same... Is it due to the input data type (uint8 and float32)? I'm having the following traceback even on a dataset in the 0-255 range. Would I need to convert my images to uint8 before cutting them?
> 
> > Traceback (most recent call last):
> > File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
> > result = (True, func(*args, **kwds))
> > File "/usr/local/lib/python3.7/dist-packages/mxnet/gluon/data/dataloader.py", line 429, in _worker_fn
> > batch = batchify_fn([_worker_dataset[i] for i in samples])
> > File "/usr/local/lib/python3.7/dist-packages/mxnet/gluon/data/dataloader.py", line 429, in 
> > batch = batchify_fn([_worker_dataset[i] for i in samples])
> > File "/content/gdrive/MyDrive/Colab Notebooks/resuneta/src/ISPRSDataset.py", line 86, in **getitem**
> > base, mask = self._transform(base, mask)
> > File "/content/gdrive/MyDrive/Colab Notebooks/resuneta/src/semseg_aug_cv2.py", line 113, in **call**
> > return next(self.iterator)(_img,_mask)
> > File "/content/gdrive/MyDrive/Colab Notebooks/resuneta/src/semseg_aug_cv2.py", line 105, in rand_shit_rot_zoom
> > return self._shift_rot_zoom(_img,_mask,tuple(center),angle,scale) #, tuple(center),angle,scale
> > File "/content/gdrive/MyDrive/Colab Notebooks/resuneta/src/semseg_aug_cv2.py", line 50, in _shift_rot_zoom
> > tRotMat = cv2.getRotationMatrix2D(_center, _angle, _scale)
> > TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type
> 
> Oh, and thanks for the help!

@feevos disregard what I reported. The problem was that Google Colab updated the opencv library to 4.6. I went back to version 4.1.0.25. I will test what you recommended and come back soon to report.
Thanks!

**Comment by feevos** [comment]
@henrique-vb  actually I tihnk I had a similar issue with opencv versions!!! If you don't know them, take a look at Albumentations and Kornia for data augmentations, I replaced all my pipelines with them these days. Let me know how you go, I hope you resolve it :) You can post code here too if you want me to take a look. 

Cheers
