### ISSUE TITLE
Can there be a torch version?

### ISSUE THREAD

**Issue by Jacky-Android** [feevos/resuneta#16]
Although mxnet is very powerful, ask for a torch version. Don't know how to run the code, it's really bad.😎Or how to train a model using mxnet.I know this is rude, sorry!

**Comment by feevos** [comment]
I am really sorry @Jacky-Android  I don't have time to port the code to pytorch as well :(. My next repository will be in pytorch though, almost there now (same topic).  

Cheers

**Comment by Jacky-Android** [comment]
> I am really sorry @Jacky-Android  I don't have time to port the code to pytorch as well :(. My next repository will be in pytorch though, almost there now (same topic).  
> 
> 
> 
> Cheers

**Comment by Jacky-Android** [comment]
Thank you for your reply and look forward to your new warehouse.
> I am really sorry @Jacky-Android  I don't have time to port the code to pytorch as well :(. My next repository will be in pytorch though, almost there now (same topic).  
> 
> 
> 
> Cheers
